config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :offres
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dashboard#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new

    if user.applicant? # demandeur ICI AJOUTER METHODE "postuler" APRÈS "read"
      can [:show, :read], Offre, user_id: user.id

    elsif user.employer? # offreur
      can :manage, Offre
      
    elsif user.admin?
      can :manage, :all

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offre.rb
class Offre < ActiveRecord::Base
	belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :offres, dependent: :destroy
  
	 
  def applicant?
    has_role?(:applicant)
  end 

  def admin?
    has_role?(:admin)
  end

  def employer?
    has_role?(:employer)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end


 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/offres_controller.rb
class OffresController < ApplicationController
  load_and_authorize_resource
  before_action :set_offre, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
 
  def index
    @offres = Offre.all
  end
 
  def show
  end
 
  def new
    @offre = Offre.new
  end
 
  def edit
  end
 
  def create
    @offre = Offre.new(offre_params)
    @offre.user = current_user
    if @offre.save
      redirect_to @offre, notice: 'Une offre a été crée avec succès.'
    else
      render :new
    end
  end
 
  def update
    if @offre.update(offre_params)
      redirect_to @offre, notice: 'Une offre a été mise à jour avec succès.'
    else
      render :edit
    end
  end
 
  def destroy
    @offre.destroy
    redirect_to offres_url, notice: 'Une offre a été supprimée avec succès.'
  end
 
  private
  def set_offre
    @offre = Offre.find(params[:id])
  end
 
  def offre_params
    params.require(:offre).permit(:name, :job, :descr, :salary)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boostrap_class(alert)
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
      danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
        concat(content_tag(:button, id: "close-button", class: "close", type: :button, data: { dismiss: 'alert' }, "aria-label" => :Close) do
          concat content_tag(:span, "&times;".html_safe, "aria-hidden" => true)
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/views/dashboard/index.html.erb
<%= flash_messages %>
<div class="block">
	<header class="header-group">
		<p>

<h2>> Fonctionnalitées :</h2><br/>
<ul>
	<li>Système d'inscription / d'authentification avec Gem Devise</li>
	<li>Gestion de roles avec Gem Rolify </li>
	<li>Gestion des droits avec Gem Cancancan</li>
	<li>Gestions et publications d'annonces avec un compte employeur</li>
	<li>Consulter et postuler a une annonce avec un compte demandeur</li>
</ul>
<br/>

<h3>> COMPTES DISPONIBLES :</h3><br/>

<p>Lors de la création d'un compte, celui-ci est par défaut un compte demmandeur, il n'y a pas la possibilité de créer de compte employeur</p>

<h4>compte employeur :</h4>

<ul>
	<li>email : offreur@gmail.com</li>
	<li>mot de passe : azerty</li>
</ul>

<h4>compte demmandeur : </h4>
<ul>
	<li>email : demandeur@gmail.com</li>
	<li>mot de passe : azerty</li>
</ul>

<br/>
<br/>
<p>Un role admin été ajouté afin d'avoir un controle total sur les fonctionnalité du site</p>

<ul>
	<li>email : admin@gmail.com</li>
	<li>mot de passe : adminadmin</li>
</ul>


	</header>
	<div class="row">
		<div class="col-md-12">
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoleEmploi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <link rel="stylesheet" href="http://poleEmploi.com/assets/bootstrap.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="css/custom.css" rel="stylesheet">

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            
            <!-- Logo-->
            <div class="navbar-header">
                <a class="navbar-brand" href="/"> <%= image_tag "logo.png" %> </a>
            </div>

            <!-- Navbar HEADER -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Offres <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Liste des offres", offres_path %></li>
                      <li><%= link_to "Ajouter une offre", new_offre_path %></li>
                    </ul>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mon compte<span class="caret"></span></a>
                      <ul class="dropdown-menu">

                       <% if user_signed_in? %>
                        <li><%= link_to "Gestion de compte", edit_user_registration_path %></li>
                      <% else %>
                        <li><%= link_to "S'enregistrer", new_user_registration_path %></li>
                        <li><%= link_to "S'authentifier", new_user_session_path %></li>
                      <% end %>
                      <% if user_signed_in? %>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
                      <% end %>
                      
                      </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="main-container" class="container mainContent">

      <section class="content content-2 blankk"> 
        <%= yield %>
      </section> 
    </div>

 </body>

    <!-- jQuery -->
    <script src="js/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="js/custom.js"></script>

 
</html>

app/views/offres/_form.html.erb
<%= form_for(@offre) do |f| %>
  <% if @offre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offre.errors.count, "error") %> prohibited this offre from being saved:</h2>
      <ul>
      <% @offre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Intitulé %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  </div>
   <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Mission %><br>
    <%= f.text_field :job, class: "form-control" %>
  </div>
  </div>
   <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Description %><br>
    <%= f.text_field :descr, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :Salaire %><br>
    <%= f.text_field :salary, class: "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit 'Créer', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/offres/edit.html.erb
<h2>Modifier une offre</h2>

<%= render 'form' %>

<%= link_to 'Afficher', @offre, class: "btn btn-warning" %>
<%= link_to 'Retour', offres_path, class: "btn btn-default" %>

app/views/offres/index.html.erb
<%= flash_messages %>
<h2>Liste des offres</h2>
<div class="offre-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-2">Intitulé</th>
       <th class="col-md-2">Poste</th>
       <th class="col-md-2">Mission</th>
       <th class="col-md-2">Salaire</th>
       <th class="col-md-2">Recruteur</th>
       <th class="col-md-4">Options</th>

      </tr>
    </thead>
    <tbody>
      <% @offres.each do |offre| %>
        <tr>
         <td class="col-md-2"><%= offre.name %></td>
         <td class="col-md-2"><%= offre.job %></td>
         <td class="col-md-2"><%= offre.descr %></td>
         <td class="col-md-2"><%= offre.salary %></td>
         <td class="col-md-2"><%= offre.user.try(:email) %></td>
         <td class="col-md-4">
            <%= link_to 'Afficher', offre_path(offre), class: "btn btn-info" %>
            <%= link_to 'Modifier', edit_offre_path(offre), class: "btn  btn-warning" %>
            <%= link_to 'Supprimer', offre_path(offre), method: :delete, data: { confirm: 'Etes vous sûr ?' }, class: "btn btn-danger" %>
         </td>
     </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'Nouvelle Offre', new_offre_path, class: "btn btn-primary" %>

app/views/offres/new.html.erb
<h2>Nouvelle offre</h2>

<%= render 'form' %><%= link_to "Retour", offres_path, class: "btn btn-default" %>

app/views/offres/show.html.erb
<%= flash_messages %>
<h2>Détails de l'offre</h2>

<p>
  <strong>Intitulé:</strong>
  <%= @offre.name %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @offre.job %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offre.descr %>
</p>

<p>
  <strong>Salaire:</strong>
  <%= @offre.salary %>
</p>

<%= link_to 'Modifier', edit_offre_path(@offre), class: "btn btn-warning" %>
<%= link_to "Retour", offres_path , class: "btn btn-default" %>